
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Login from '@/components/Auth/Login'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'BunnyShop',
  description: 'Generated by BunnyShop',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
 
  return (

    <html lang="en">
      
      <body className={inter.className}>
        <Login/>
          <Navbar/>
          
          {children}
       
      </body>
    </html>
  )
}
