
import type { Metadata } from 'next'
import './globals.css'
import Navbar from '@/components/NavBar/Navbar'
import Login from '@/components/Auth/Login'
import { Inter as FontSans } from "next/font/google"
import Footer from '@/components/Footer/Footer'
import { cn } from '@/lib/utils'

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})
export const metadata: Metadata = {
  title: 'BunnyShop',
  description: 'Generated by BunnyShop',
  icons: {
    icon:['/favicon.ico?v=4'],
    apple:['/apple-touch-icon.png?v=4'],
    shortcut:['/apple-touch-icon.png']
  },
  manifest: "/site.webmanifest"
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
 
  return (

    <html lang="en">
      <body className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}>
          
          <Navbar/>
          
          {children}
          <Footer/>
      </body>
      
    </html>
  )
}
