
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/NavBar/Navbar'
import Login from '@/components/Auth/Login'
const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'BunnyShop',
  description: 'Generated by BunnyShop',
  icons: {
    icon:['/favicon.ico?v=4'],
    apple:['/apple-touch-icon.png?v=4'],
    shortcut:['/apple-touch-icon.png']
  },
  manifest: "/site.webmanifest"
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
 
  return (

    <html lang="en">
      <body className={inter.className}>
          
          <Navbar/>
          
          {children}
       
      </body>
    </html>
  )
}
